apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd1-ingress-mysql-ns
  namespace: mysql
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: pmahimanshu324.duckdns.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: phpmyadmin-service
            port:
              number: 8000