apiVersion: v1
kind: Secret
metadata:
  name: duckdns-token
  namespace: cert-manager
type: Opaque
data:
  # The token value below must be base64 encoded!
  token: YmQyMmQwMTYtOTEwYS00NjliLWJjN2MtYTllY2Y5YmM0NTdj