require('dotenv').config();
const express = require('express');
const prisma = require('./db/connection'); // Connection instance created earlier

const app = express();
app.use(express.json());

// ---------------------------------------------------------------------------
// 1. HELPER: Save Error Log to MongoDB via Prisma
// ---------------------------------------------------------------------------
async function saveErrorToDb(errorMessage, metadata = {}) {
  try {
    // Note: Prisma maps model "ErrorLog" or "error_log" to prisma.errorLog or prisma.error_log
    // If your schema model name is error_log, access it via prisma.error_log
    const errorModel = prisma.errorLog || prisma.error_log;

    const savedLog = await errorModel.create({
      data: {
        service: 'nodejs-express-app',
        message: errorMessage,
        path: metadata.path || null,
        method: metadata.method || null,
        statusCode: metadata.statusCode ? parseInt(metadata.statusCode) : 500,
        isProcessed: false,
        aiAnalysis: null
      }
    });

    console.log(`[DB Logged - ID: ${savedLog.id}]: ${errorMessage}`);
    return savedLog;
  } catch (err) {
    console.error('Failed to save error log to MongoDB:', err.message);
  }
}

// ---------------------------------------------------------------------------
// 2. HELPER: Read Unprocessed Error Logs from MongoDB
// ---------------------------------------------------------------------------
async function getUnprocessedErrors() {
  try {
    const errorModel = prisma.errorLog || prisma.error_log;

    const pendingErrors = await errorModel.findMany({
      where: { isProcessed: false },
      orderBy: { createdAt: 'desc' },
      take: 10
    });

    console.log(`\n--- Fetched ${pendingErrors.length} Unprocessed Error Logs from MongoDB ---`);
    return pendingErrors;
  } catch (err) {
    console.error('Failed to query error logs from MongoDB:', err.message);
  }
}

// ---------------------------------------------------------------------------
// 3. WRAPPER: Catch async errors in route handlers automatically
// ---------------------------------------------------------------------------
const asyncHandler = (fn) => (req, res, next) => {
  Promise.resolve(fn(req, res, next)).catch(next);
};

// Mock User Database
const users = [
  { id: '1', name: 'Alice' },
  { id: '2', name: 'Bob' },
  { id: '3', name: 'Charlie' }
];

// ---------------------------------------------------------------------------
// 4. ROUTES
// ---------------------------------------------------------------------------

// User Search Route
app.get(
  '/api/backend/users/:id',
  asyncHandler(async (req, res) => {
    const userId = req.params.id;

    // Simulate thrown error for specific userId "999"
    if (userId === '999') {
      const error = new Error(`Database error: User ID ${userId} is restricted or corrupted!`);
      error.statusCode = 500;
      throw error;
    }

    // Bug simulation: reference undefined variable to trigger runtime Error
    const user = users.find((u) => u.id === userId);

    if (!user) {
      const error = new Error(`User with ID ${userId} not found.`);
      error.statusCode = 404;
      throw error;
    }

    res.json({ success: true, user });
  })
);

// Route 1 for AI Agent: Fetch all unprocessed errors
app.get(
  '/api/backend/logs/unprocessed',
  asyncHandler(async (req, res) => {
    const pendingLogs = await getUnprocessedErrors();
    res.json({ success: true, count: pendingLogs.length, data: pendingLogs });
  })
);

// Route 2 for AI Agent: Mutate error record by ID after LLM processing
app.patch(
  '/api/backend/logs/:id/process',
  asyncHandler(async (req, res) => {
    const { id } = req.params;
    const { aiAnalysis } = req.body; // Analysis generated by LLM

    const errorModel = prisma.errorLog || prisma.error_log;

    const updatedLog = await errorModel.update({
      where: { id: id },
      data: {
        isProcessed: true,
        aiAnalysis: aiAnalysis || 'AI Agent processed and resolved issue.'
      }
    });

    console.log(`[DB Mutated - ID: ${id}]: Marked as processed.`);
    res.json({ success: true, message: 'Log marked as processed', data: updatedLog });
  })
);

// ---------------------------------------------------------------------------
// 5. GLOBAL ERROR HANDLING MIDDLEWARE (Saves all thrown errors to MongoDB)
// ---------------------------------------------------------------------------
app.use(async (err, req, res, next) => {
  const statusCode = err.statusCode || 500;
  const errorMessage = err.message || 'Internal Server Error';

  // Save error details directly into MongoDB Atlas via Prisma
  await saveErrorToDb(errorMessage, {
    path: req.path,
    method: req.method,
    statusCode: statusCode.toString()
  });

  res.status(statusCode).json({
    success: false,
    error: errorMessage
  });
});

// Start Server
const PORT = 8000;
app.listen(PORT, () => {
  console.log(`Server running on http://localhost:${PORT}`);
});

///////