apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ai-agent-microservice
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/himanshusarma074/ai-monitoring-project.git
    targetRevision: HEAD
    path: k8s-infra/platform-stack/microservices/ai-agent
  ignoreDifferences:
  - group: ""
    kind: Service
    jsonPointers:
    - /spec/selector/rollouts-pod-template-hash
    managedFieldsManagers:
    - argo-rollouts
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      # - ServerSideApply=true