[public]
frontend_server ansible_host=44.215.67.63

[private]
backend_server_1 ansible_host=10.0.1.x  # Your Private IP
backend_server_2 ansible_host=10.0.2.x

[private:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/my-aws-key.pem
# The Magic: Tunnel through the Public Instance
ansible_ssh_common_args='-o ProxyCommand="ssh -W %h:%p -q ubuntu@35.172.x.x -i ~/.ssh/my-aws-key.pem"'