# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: cert-manager
#   namespace: argocd
# spec:
#   project: default
#   sources:
#     # Source 1: cert-manager
#     - repoURL: https://charts.jetstack.io
#       chart: cert-manager
#       targetRevision: v1.14.5
#       helm:
#         values: |
#           installCRDs: true
#     # Source 2: Updated DuckDNS Webhook Repository
#     - repoURL: https://csp33.github.io/cert-manager-duckdns-webhook/
#       chart: cert-manager-webhook-duckdns
#       targetRevision: 1.15.0 # Use the latest version from this repo
#       helm:
#         values: |
#           duckdns:
#             token: "bd22d016-910a-469b-bc7c-a9ecf9bc457c"
#           certManager:
#             namespace: cert-manager
#     # Source 3: Your local config
#     - repoURL: https://github.com/HimanshuSarma/argocd1.git
#       targetRevision: HEAD
#       ref: values
#       path: k8s-infra/platform-stack/cert-management
#   destination:
#     server: https://kubernetes.default.svc
#     namespace: cert-manager
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
#     syncOptions:
#       - CreateNamespace=true
#       - ServerSideApply=true