apiVersion: v1
kind: Pod
metadata:
  name: httpd-pod
  labels:
    app: httpd
spec:
  containers:
  - name: httpd-container
    image: httpd:latest
    ports:
    - containerPort: 80    
    resources:
      requests:
        memory: "15Mi"     # Request 64 Megabytes of RAM to start
        cpu: "100m"       # Request 0.25 of a CPU core
      limits:
        memory: "20Mi"    # Hard ceiling: kill container if it goes past 128MB
        cpu: "100m"       # Hard ceiling: throttle container if it hits 0.5 of a core