[backend_servers_group1]
backend-server-0 ansible_host=127.0.0.1 ansible_port=2221
backend-server-1 ansible_host=127.0.0.1 ansible_port=2222

[backend_servers_group2]
backend-server-2 ansible_host=127.0.0.1 ansible_port=2223
backend-server-3 ansible_host=127.0.0.1 ansible_port=2224